name: Deployment pipeline
on: [push, workflow_dispatch] # Run on every

jobs:  
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"

  lint:
    runs-on: ubuntu-latest
    steps:       
      - name: Get code
        uses: actions/checkout@v3        
      - name: Install dependencies
        uses: actions/setup-node@v4    
        with:
          node-version: 18
      - run: |
          npm ci
          node --version
      - name: Lint
        run: npm run lint  

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v4    
        with:
          node-version: 18
      - run: |
          npm ci
          node --version
      - name: Test code
        run: npm run test      
          
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v4    
        with:
          node-version: 18
      - run: npm ci         
      - name: Build code
        run: |
          npm run build
          node --version
      - name: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist
            test-results

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: Output contents
        run: ls -R
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v4    
        with:
          node-version: 18
      - run: |
          npm ci
          node --version
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying..."