name: First Workflow
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]
  
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab
jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it      
      - name: Run a one-line script
        run: echo Hello, world!      
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
